[project]
name = "benchmark_status_checker"
version = "0.1.0"
description = "Power up your crews with benchmark_status_checker"
readme = "README.md"
requires-python = ">=3.10,<3.13"
dependencies = [
    "crewai[tools]>=0.121.0"
]

[tool.crewai]
type = "tool"
